version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: marvin
      POSTGRES_PASSWORD: 0791425789
      POSTGRES_DB: crud
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - .env.production
    depends_on:
      - db
    command: >
      sh -c "
        echo 'Waiting for DB...' &&
        until nc -z db 5432; do sleep 2; done &&
        echo 'Running Prisma migrations...' &&
        npx prisma migrate deploy &&
        echo 'Starting app...' &&
        node dist/server.js
      "
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health']
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:7
    ports:
      - '6379:6379'

volumes:
  postgres-data:
